Update

diff --git a/app/src/main/assets/home/bin/apexeditor b/app/src/main/assets/home/bin/apexeditor
--- a/app/src/main/assets/home/bin/apexeditor
+++ b/app/src/main/assets/home/bin/apexeditor
@@ -1,141 +1,169 @@
 #!/data/data/com.tool.tree/files/home/bin/bash
-
+# Kakathic
 source language
-show_help() {
-  echo "Usage: apexeditor -i <input> -o <output> <flags>"
-  echo
-  echo "  -i    input path"
-  echo "  -o    output path"
-  echo "  -s    feature options:"
-  echo "            decom: decode apex for editor"
-  echo "            build: rebuild the apex project"
-  echo "  -a    build Apex with API: auto"
-  echo "            auto: default apex"
-  echo "            30: Android 11"
-  echo "            31: Android 12"
-  echo "            32: Android 12L"
-  echo "            33: Android 13"
-  echo "            34: Android 14"
-  echo "            35: Android 15"
-  echo "            36: Android 16"
-  echo "            37: Android 17"
-  echo "  -c    compress apex into capex: 0"
-  echo "            0: uncompressed"
-  echo "            1: compressed"
-  echo "  -d    Delete the project after construction is completed: 0"
-  echo "            0: no"
-  echo "            1: yes"
-  echo "  -k    choose a signature to sign on Apex: com.android.example.apex"
-  echo "  -f    select the apex_payload partition format: auto"
-  echo "            auto: automatic mode"
-  echo "            ext4: create partitions with ext4"
-  echo "            erofs: create partitions with erofs"
-  echo "            f2fs: create partitions with f2fs"
-  echo "  sample: apexeditor -s decom -i path/file.[apex,capex] -o path/dir"
-  echo "  sample: apexeditor -s build -f auto -a auto -k com.android.example.apex -c 0 -d 0 -i path/dir -o path/dir"
-  echo "  -h    show help"
-  exit 1
+
+do_decode() {
+  local input="" output="$APK/$PTAH"
+
+  while [ $# -gt 0 ]; do
+    case "$1" in
+    -i|--input) input="$2"; shift 2 ;;
+    -o|--output) output="$2"; shift 2 ;;
+    *)
+    echo "Decode: Unknown flag $1" >&2;
+    exit 1
+    ;;
+    esac
+  done
+
+  if [[ -z "$input" ]] || [[ ! -f "$input" ]]; then
+    echo "Missing parameter error" >&2
+    echo "-i|--input: $input" >&2
+    exit 1
+  fi
+
+  echo "$more_text_4 $input"
+
+  ten_file="$(echo "${input##*/}" | sed -e 's|\.apex$||' -e 's|\.capex$||')"
+  tm_save="$output/$ten_file"
+  apex_type="$(checkapk "$input")"
+  [ -d "$tm_save" ] && rm -fr "$tm_save"
+  mkdir -p "$tm_save/apex" "$tm_save/.cache"
+  echo "$apex_type" > "$tm_save/.cache/type"
+  
+  if [ "$apex_type" == "capex" ]; then
+    unzip -oq "$input" original_apex -d "$tm_save"
+    apkeditor d -f -t raw -i "$tm_save/original_apex" -o "$tm_save/apex" &>"$tm_save/.cache/apex_decode.log" || killtree "$(cat "$tm_save/.cache/apex_decode.log")"
+    rm -f "$tm_save/original_apex"
+    else
+    apkeditor d -f -t raw -i "$input" -o "$tm_save/apex" &>"$tm_save/.cache/apex_decode.log" || killtree "$(cat "$tm_save/.cache/apex_decode.log")"
+  fi
+
+  if [ -f "$tm_save/apex/root/apex_payload.img" ]; then
+    unpack_img -i "$tm_save/apex/root/apex_payload.img" -o "$tm_save" -d 1 &>>"$tm_save/.cache/apex_decode.log" || killtree "$(cat "$tm_save/.cache/apex_decode.log")"
+    rm -f "$tm_save/config/apex_payload_size.txt"
+  else
+    echo "Error: Item not found: apex_payload.img" >&2
+  fi
+
+  if [ -f "$tm_save/apex/root/apex_build_info.pb" ]; then
+  protoc_pb.py -d "$tm_save/apex/root/apex_build_info.pb" -o "$tm_save/apex_build_info.xml"
+  fi
+
 }
 
-if [[ $# -eq 0 || "$1" != -* ]]; then
-show_help
-fi
+do_build() {
+  local input="" output="$PTAD/out" key="testkey" compressed="auto" delete=0
 
-INPUT=''; OUTPUT=''; SELECT=''; show_help='';
-APIREPAK=''; COMPEV=''; DELLAPX=''; SIGNAPX=''; PTTTYPE='';
-while getopts ":i:o:s:p:a:c:d:k:f:h" opt; do
-  case $opt in
-    i) INPUT="$OPTARG" ;;
-    o) OUTPUT="$OPTARG" ;;
-    s) SELECT="$OPTARG" ;;
-    a) APIREPAK="$OPTARG" ;;
-    c) COMPEV="$OPTARG" ;;
-    d) DELLAPX="$OPTARG" ;;
-    k) SIGNAPX="$OPTARG" ;;
-    f) PTTTYPE="$OPTARG" ;;
-    h) show_help ;;
-    \?) echo "! Not understand -$OPTARG"; show_help ;;
-    :) echo "! Lack of value for -$OPTARG"; show_help ;;
-  esac
-done
+  while [ $# -gt 0 ]; do
+    case "$1" in
+    -i|--input) input="$2"; shift 2 ;;
+    -o|--output) output="$2"; shift 2 ;;
+    -k|--key) key="$2"; shift 2 ;;
+    -c|--compressed) compressed="$2"; shift 2 ;;
+    -d|--delete) delete="$2"; shift 2 ;;
+    *)
+    echo "Build: Unknown flag $1" >&2;
+    exit 1
+    ;;
+    esac
+  done
 
-if [[ -z "$INPUT" || -z "$OUTPUT" || -z "$SELECT" ]]; then
-echo "Lack of value:
--i $INPUT
--o $OUTPUT
--s $SELECT" >&2
-exit 1
-fi
+  if [[ -z "$input" ]] || [[ ! -d "$input" ]]; then
+    echo "Missing parameter error" >&2
+    echo "-i|--input: $input" >&2
+    exit 1
+  fi
 
-# mặc định có sẵn
-[ -z "$APIREPAK" ] && APIREPAK='auto'
-[ -z "$COMPEV" ] && COMPEV=0
-[ -z "$DELLAPX" ] && DELLAPX=0
-[ -z "$SIGNAPX" ] && SIGNAPX='com.android.example.apex'
-[ -z "$PTTTYPE" ] && PTTTYPE='auto'
+  mkdir -p "$output"
+  echo "$apkb_text_1 ${input##*/}"
+  echo
+  
+  [ -f "$input/apex_build_info.xml" ] && protoc_pb.py -e "$input/apex_build_info.xml" -o "$input/apex/root/apex_build_info.pb"
+  
+  if [ -d "$input/apex_payload" ]; then
+  repack_img -i "$input/apex_payload" -o "$input/apex/root" -d 0 &>"$input/.cache/apex_build.log" || killtree "$(cat "$input/.cache/apex_build.log")"
+  
+  seva_payload="$input/apex/root/apex_payload.img"
+  # Ký avbtool
+  avbtool add_hashtree_footer \
+  --do_not_generate_fec \
+  --algorithm SHA256_RSA4096 \
+  --hash_algorithm sha256 \
+  --key "$ETC/key/4096/${key}.pem" \
+  --prop "apex.key:$key" \
+  --salt "$(checksum "$input/apex/root/apex_manifest.pb")" \
+  --image "$seva_payload"
+  
+  INFO=$(avbtool info_image --image "$seva_payload")
+  VBMETA_OFFSET=$(echo "$INFO" | grep "VBMeta offset:" | awk '{print $3}')
+  VBMETA_SIZE=$(echo "$INFO" | grep "VBMeta size:" | awk '{print $3}')
+  PARTITION_SIZE=$(( ((VBMETA_OFFSET + VBMETA_SIZE + 4095) / 4096 * 4096) + 4096 ))
+  avbtool resize_image --image "$seva_payload" --partition_size "$PARTITION_SIZE"
 
-if [ "$SELECT" == 'decom' ]; then
-echo "$more_text_4 ${INPUT##*/}"
-echo
-# giải mã apex, capex
-ten_file="$(echo "${INPUT##*/}" | sed -e 's|\.apex$||' -e 's|\.capex$||')"
-deapexer.py extract -d "$OUTPUT/$ten_file" "$INPUT"
-# lấy API, name
-unzip -oq "$INPUT" AndroidManifest.xml -d "$OUTPUT/$ten_file" &>/dev/null
-echo -e "api: $(axmlprinter "$OUTPUT/$ten_file/AndroidManifest.xml" | grep -m1 'android:compileSdkVersion=' | cut -d\" -f2)" >>"$OUTPUT/$ten_file"/apex_infor.ini
-rm -fr "$OUTPUT/$ten_file/AndroidManifest.xml"
-# kết thúc
-fi
+  avbtool extract_public_key --key "$ETC/key/4096/${key}.pem" --output "$input/apex/root/apex_pubkey"
+  
+  else
+  echo "Error: Item not found: $output" >&2
+  fi
+  
+  if [ -d "$input/apex" ]; then
+  apkeditor b -f -i "$input/apex" -o "$input/${input##*/}.apex" &>>"$input/.cache/apex_build.log" || killtree "$(cat "$input/.cache/apex_build.log")"
+  fi
+  
+  if [ -f "$input/${input##*/}.apex" ]; then
+  signapk -a 4096 "$ETC/key/${key}.x509.pem" "$ETC/key/${key}.pk8" "$input/${input##*/}.apex" "$input/${input##*/}_sign.apex"
+  [ -f "$input/${input##*/}_sign.apex" ] || killtree "Apex sign error, please check again!"
+  fi
+  
+  if [ "$compressed" == "0" ]; then
+  nen_apex=0
+  elif [ "$compressed" == "1" ]; then
+  nen_apex=1
+  else
+  [ "$(cat "$input/.cache/type")" == "capex" ] && nen_apex=1 || nen_apex=0
+  fi
+  
+  if [ "$nen_apex" == 1 ]; then
+    apex_compression_tool.py compress -k "$key" --input "$input/${input##*/}_sign.apex" --output "$output/${input##*/}.capex"
+    echo "$save_text $output/${input##*/}.capex"
+  else
+    mv "$input/${input##*/}_sign.apex" "$output/${input##*/}.apex"
+    echo "$save_text $output/${input##*/}.apex"
+  fi
 
-if [ "$SELECT" == 'build' ]; then
-echo "$apkb_text_1 ${INPUT##*/}"
-echo
-# Kiểm tra chữ ký
-if [ "$(openssl rsa -in "$ETC/key/4096/$SIGNAPX.pem" -text -noout | grep -cm1 '4096 bit')" != 1 ]; then
-killtree "Not a 4096-bit signature, verification failed."
-else
-echo "I: Verify signature 4096 bit success: $SIGNAPX.pem"
-cp -rf "$ETC/key/4096/$SIGNAPX.pem" "$TMP/apex.key.pem"
-cp -rf "$ETC/key/$SIGNAPX.pk8" "$TMP/apex.key.pk8"
-cp -rf "$ETC/key/$SIGNAPX.x509.pem" "$TMP/apex.key.x509.pem"
-avbtool extract_public_key --key "$TMP/apex.key.pem" --output "$TMP/apex.key.avbpubkey"
-fi
-# lấy api
-if [ "$APIREPAK" == 'auto' ]; then
-API="$(grep 'api: ' "$INPUT/apex_infor.ini" | awk '{print $2}')"
-# tự động hạ api
-while true; do
-if [ -f "$HOME/.local/share/apktool/framework/1-$API.apk" ]; then
-break
-else
-API=$((API - 1))
-fi
-done
-else
-API="$APIREPAK"
-fi
-# xây dựng apex
-mkdir -p "$OUTPUT"
-echo "I: Build apex with API: $API"
-if [ "$PTTTYPE" == 'auto' ]; then
-PTTTYPE="$(grep 'fscon: ' "$INPUT/apex_infor.ini" | awk '{print $2}')"
-fi
-echo "I: Build apex_payload in format: $PTTTYPE"
-apexer.py -f -p "$INPUT" --api $API --payload_fs_type $PTTTYPE "$OUTPUT/${INPUT##*/}.apex"
-# nén lại apex thành capex
-if [ -f "$OUTPUT/${INPUT##*/}.apex" ]; then
-    if [ "$COMPEV" == 1 ]; then
-    apex_compression_tool.py compress --input "$OUTPUT/${INPUT##*/}.apex" --output "$OUTPUT/${INPUT##*/}.capex"
-    [ -f "$OUTPUT/${INPUT##*/}.capex" ] && rm -fr "$OUTPUT/${INPUT##*/}.apex" || killtree "Apex compression failed !"
-    fi
-else
-killtree "Apex build failed !"
-fi
-# kiểm tra hoàn thành
-    if [[ -f "$OUTPUT/${INPUT##*/}.apex" || -f "$OUTPUT/${INPUT##*/}.capex" ]]; then
-    [ "$DELLAPX" == 1 ] && rm -fr "$INPUT"
-    fi
-# kết thúc
-fi
+  # dọn dẹp
+  if [ "$delete" == 1 ]; then
+  rm -fr "$input"
+  else
+  rm -fr "$input"/*.apex
+  fi
+  
+}
 
+# --- Điểm bắt đầu của Script ---
+COMMAND="$1"
+shift 2>/dev/null
 
+case "$COMMAND" in
+  d|decode)
+  do_decode "$@"
+  ;;
+  b|build)
+  do_build "$@"
+  ;;
+  *)
+  echo "Usage: apexeditor [decode|build] [options]"
+  echo "decode:"
+  echo "-i|--input: file.[apex,capex]"
+  echo "-o|--output: folder_out"
+  echo
+  echo "build:"
+  echo "-i|--input: folder_input"
+  echo "-o|--output: folder_out"
+  echo "-k|--key: name_sign (default: testkey)"
+  echo "-c|--compressed: [auto,0,1] (default: auto)"
+  echo "-d|--delete: [0,1]"
+  exit 1
+  ;;
+esac
