Update

diff --git a/app/src/main/assets/home/bin/check_add b/app/src/main/assets/home/bin/check_add
--- a/app/src/main/assets/home/bin/check_add
+++ b/app/src/main/assets/home/bin/check_add
@@ -1,21 +1,27 @@
 # Kakathic
 
 show_all() {
-  showbanner -y "$1" -t "$name_add" -m "$2"
+  showbanner -y "$1" -t "$name" -m "$2"
 }
 
-if [ ! -f "$1/check" ]; then
+if [ ! -f "$1/zcheck" ]; then
   if checkonline; then
     source language 2>/dev/null
-    name_add="$(gprop name $1/download.prop)"
-    file_name="$(gprop url $1/download.prop)"
-    check_sum_onl="$(xem https://api.github.com/repos/Zenlua/Tool-Tree/releases/tags/V1 | jq -r --arg name "${file_name##*/}" '.assets[] | select(.name == $name) | .digest' | cut -d: -f2)"
-    if [[ "$check_sum_onl" ]] && [[ "$check_sum_onl" != "$(glog check_sum_addon_${1##*/})" ]]; then
-    show_all info "$updating_text add-on: $name_add"
-    installadd "$file_name" "${1%/*}" &>/dev/null && show_all success "$update_text $flash_text_12: $name_add $(gprop version $1/addon.prop) ($(gprop versionCode $1/addon.prop))" || show_all error "$load_text_2 $name_add"
+    source "$1/download.prop" 2>/dev/null
+    sumcek="$(xem https://api.github.com/repos/Zenlua/Tool-Tree/releases/tags/V1 | jq -r --arg name "${url##*/}" '.assets[] | select(.name == $name) | .digest' | cut -d: -f2)"
+    if [[ "$sumcek" ]] && [[ "$sumcek" != "$(glog sumcek_$id)" ]]; then
+      show_all info "$updating_text add-on: $name"
+      installadd "$url" "${1%/*}" &>/dev/null
+      if [ $? == 0 ]; then
+        source "$1/Add-on.bash" 2>/dev/null
+        show_all success \
+        "$update_text $flash_text_12: $name $version ($versionCode)"
+      else
+        show_all error "$load_text_2 $name"
+      fi
     fi
   else
-    echo "Network error $name_add"
+    echo "Network error $name"
   fi
-  echo > "$1/check"
+  echo > "$1/zcheck"
 fi
