Upload file

diff --git a/pio/src/main/assets/home/bin/repack_img b/pio/src/main/assets/home/bin/repack_img
--- a/pio/src/main/assets/home/bin/repack_img
+++ b/pio/src/main/assets/home/bin/repack_img
@@ -146,7 +146,7 @@ fi
 
 if [ "$partition" == "erofs" ];then
   [ "$DISATFS" == 1 ] || patch "$INPUT" "$fs_config" "$file_contexts" >/dev/null
-  mkfs.erofs --quiet -T $time_build --workers=$threads -z${NENEROFS}${zlsize} --mount-point="/${INPUT##*/}" --fs-config-file="$fs_config" --file-contexts="$file_contexts" "$saved" "$INPUT" 2>$TMP/mkfs_erofs.log || abort "Error build process mkfs.erofs, log: $TMP/mkfs_erofs.log" "$saved"
+  mkfs.erofs --quiet -T $time_build --workers=$threads -z${NENEROFS}${zlsize} --mount-point="/${INPUT##*/}" --fs-config-file="$fs_config" --file-contexts="$file_contexts" "$saved" "$INPUT" 2>$TMP/mkfs_erofs.log || killtree "Error build process mkfs.erofs, log: $TMP/mkfs_erofs.log" "$saved"
   echo
 elif [ "$partition" = "boot" ] || [ "$partition" = "vendor_boot" ]; then
     # xây dựng cpio
@@ -163,7 +163,7 @@ elif [ "$partition" = "boot" ] || [ "$partition" = "vendor_boot" ]; then
         else
         echo "Build DTB: $redts"
         dtc -q -I dts -O dtb -@ -o ${nrep} $redts
-        [ "$?" != 0 ] && abort "Error: Build DTB"
+        [ "$?" != 0 ] && killtree "Error: Build DTB"
         fi
     done
     for bdts in $(ls -1d cache/type_* 2>/dev/null); do
@@ -208,7 +208,7 @@ elif [ "$partition" = "dtbo" ];then
     else
     echo "Build dtb: $dtbo"
     dtc -q -I dts -O dtb -@ -o dtb.${dtbo##*.} $dtbo
-    [ "$?" != 0 ] && abort "Error: Build dtb"
+    [ "$?" != 0 ] && killtree "Error: Build dtb"
     fi
   done
   dtbo create dtbo.img $(ls -1d dtb.* | sort -n -t . -k 2) >/dev/null
@@ -217,7 +217,7 @@ elif [ "$partition" = "dtbo" ];then
   echo
 elif [ "$partition" == "f2fs" ];then
   if [ "$ROT" == 0 ];then
-  abort "Error build: f2fs, $root_warning_text"
+  killtree "Error build: f2fs, $root_warning_text"
   fi
   [ "$DISATFS" == 1 ] || patch "$INPUT" "$fs_config" "$file_contexts" >/dev/null
   if [ -f "$info_size" ] && [ "$(cat $info)" == "f2fs" ] && [ "$TTBUILDI" == 0 ];then
@@ -246,15 +246,15 @@ elif [ "$partition" == "f2fs" ];then
   fi
   [ -f "$TMP/make_f2fs.log" ] && rm -fr "$TMP/make_f2fs.log"
   if [ "$f2fsrw" == 1 ];then
-  make_f2fs -g android -O compression -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real || abort "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
+  make_f2fs -g android -O compression -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real || killtree "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
   echo " "
   sload_f2fs -t "$mount_dir" -C "$fs_config" -s "$file_contexts" -T $time_build -f "$INPUT" -c "$saved" 2>$TMP/sload_f2fs.log | tee -a $TMP/sload_f2fs.log | sed -e "/Free segments:/d" -e "/Not enough space/d"
   else
-  make_f2fs -g android -O ro -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real || abort "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
+  make_f2fs -g android -O ro -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real || killtree "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
   echo " "
   sload_f2fs -t "$mount_dir" -C "$fs_config" -s "$file_contexts" -T $time_build -f "$INPUT" "$saved" 2>$TMP/sload_f2fs.log | tee -a $TMP/sload_f2fs.log | sed -e "/Free segments:/d" -e "/Not enough space/d"
   fi
-  [ "$(grep -cm1 'Done:' $TMP/sload_f2fs.log)" == 0 ] && abort "Error build sload_f2fs, Suggestion: Increase free MB, log: $TMP/sload_f2fs.log" "$saved";
+  [ "$(grep -cm1 'Done:' $TMP/sload_f2fs.log)" == 0 ] && killtree "Error build sload_f2fs, Suggestion: Increase free MB, log: $TMP/sload_f2fs.log" "$saved";
   [ -f "$INPUT/${INPUT##*/}/build.prop" ] && rm -fr "$file_contexts" "$fs_config"
   echo
 elif [ "$partition" == "ext" ];then
@@ -271,18 +271,18 @@ elif [ "$partition" == "ext" ];then
     if [ "$e2fsdroid" == 1 ];then
     size="$(echo "$size_real / 4096" | bc)";
     mke2fs -O ^has_journal,^quota,^project,^resize_inode -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "$mount_dir" "$saved" $size 2>&1
-    e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_ext.log || abort "Error build process e2fsdroid, log: $TMP/e2fsdroid_ext.log" "$saved"
+    e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_ext.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_ext.log" "$saved"
     else
-    make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_real -a "/${INPUT##*/}" "$saved" "$INPUT" || abort "Error build process make_ext4fs" "$saved"
+    make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_real -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved"
     echo
     fi
   else
     if [ "$e2fsdroid" == 1 ];then
     size="$(echo "$size_orig / 4096" | bc)";
     mke2fs -O ^has_journal,^quota,^project,^resize_inode -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "$mount_dir" "$saved" $size 2>&1
-    e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_exts.log || abort "Error build process e2fsdroid, log: $TMP/e2fsdroid_exts.log" "$saved"
+    e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_exts.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_exts.log" "$saved"
     else
-    make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_orig -a "/${INPUT##*/}" "$saved" "$INPUT" || abort "Error build process make_ext4fs" "$saved"
+    make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_orig -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved"
     echo
     fi
     resize2fs -M "$saved" 2>&1
@@ -316,7 +316,7 @@ if [[ "$partition" =~ ^(erofs|f2fs|ext)$ ]];then
     LEVEL="$(echo "$lvnen / 2" | bc)"
     img2simg $saved >/dev/null
     img2sdat "$saved" -o "$OUTPUT/out" -v 4 -p ${INPUT##*/} >/dev/null
-    [ -f "$OUTPUT/out/${INPUT##*/}.new.dat" ] || abort "Error creating file ${INPUT##*/}.new.dat failed !!!"
+    [ -f "$OUTPUT/out/${INPUT##*/}.new.dat" ] || killtree "Error creating file ${INPUT##*/}.new.dat failed !!!"
     brotli -fq "$LEVEL" "$OUTPUT/out/${INPUT##*/}.new.dat" -o "$OUTPUT/out/${INPUT##*/}.new.dat.br" >/dev/null
     [ "$?" == 0 ] && rm -f "$saved" "$OUTPUT/out/${INPUT##*/}.new.dat"
     elif [ "$CONVER" == 'sparse' ];then
diff --git a/pio/src/main/assets/home/bin/unpak_img b/pio/src/main/assets/home/bin/unpak_img
--- a/pio/src/main/assets/home/bin/unpak_img
+++ b/pio/src/main/assets/home/bin/unpak_img
@@ -77,7 +77,7 @@ if [ "$dang_tep" == 'zstd' ];then
   zstd -T$threads -f -d -k "$INPUT" -o "$file_img" &>/dev/null
 elif [ "$dang_tep" == 'br' ] || [ "$dang_tep" == 'dat' ];then
   tenpjanvung="$(echo "${INPUT##*/}" | cut -d. -f1)"
-  [ -e "${INPUT%/*}/$tenpjanvung.transfer.list" ] || abort "$more_text_5 $tenpjanvung.transfer.list"
+  [ -e "${INPUT%/*}/$tenpjanvung.transfer.list" ] || killtree "$more_text_5 $tenpjanvung.transfer.list"
   echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
   [ "${INPUT##*.}" == 'br' ] && brotli -f -d "$INPUT" -o "$TMP/$(echo "${INPUT%.*}" | awk -F/ '{print $NF}')" &>/dev/null
   file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
@@ -88,7 +88,7 @@ elif [ "$dang_tep" == 'sparse' ];then
   simg2img "$INPUT" "$file_img"
 elif [ "$dang_tep" == 'payload' ] || [ -n "$xacnhatpay" ];then
   echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
-  payload_dumper --no-parallel --out "$TMP" --images "$PVUGBIN" "$INPUT" >/dev/null || abort "Payload unpack error"
+  payload_dumper --no-parallel --out "$TMP" --images "$PVUGBIN" "$INPUT" >/dev/null || killtree "Payload unpack error"
   file_img="$TMP/$PVUGBIN.img"
 elif [ "$dang_tep" == 'super' ];then
   echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
@@ -136,7 +136,7 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
       echo "$dang_file" > "$OUTPUT/config/${namepv##*/}_info"
     elif [ "$dang_file" == 'f2fs' ];then
       if [ "$ROT" == 0 ];then
-      abort "Error Unpack: f2fs, $root_warning_text"
+      killtree "Error Unpack: f2fs, $root_warning_text"
       fi
       #dump.f2fs -r -P -L -f -o "$OUTPUT/${namepv##*/}" "$file_img"
       mkdir -p "$TMP/${namepv##*/}"
@@ -149,12 +149,12 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
       echo "$dang_file" > "$OUTPUT/config/${namepv##*/}_info"
       echo "$(fsck.f2fs "$file_img" | grep 'superblock features' | grep -cm1 ro)" > "$OUTPUT/config/${namepv##*/}_f2fs_ro"
     elif [ "$dang_file" == 'erofs' ];then
-      extract.erofs -T$threads -x -i "$file_img" -o "$OUTPUT" >$TMP/extract_erofs.log || abort "\nextract.erofs error: ${namepv##*/}" "$OUTPUT/${namepv##*/}"
+      extract.erofs -T$threads -x -i "$file_img" -o "$OUTPUT" >$TMP/extract_erofs.log || killtree "\nextract.erofs error: ${namepv##*/}" "$OUTPUT/${namepv##*/}"
       echo "$dang_file" > "$OUTPUT/config/${namepv##*/}_info"
       if [ -f $OUTPUT/config/exception.log ];then
       rm -fr "$OUTPUT/${namepv##*/}"
       cat $OUTPUT/config/exception.log >&2
-      abort "\nIncomplete file error please check hash" $OUTPUT/config/exception.log
+      killtree "\nIncomplete file error please check hash" $OUTPUT/config/exception.log
       fi
     elif [ "$dang_file" == 'logo' ];then
     logo_dumper.py --out "$OUTPUT/${namepv##*/}" "$file_img" unpack
@@ -170,7 +170,7 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
       magiskboot unpack -h "$file_img" 2>&1
       if [ "$?" = '1' ];then
         rm -rf "$OUTPUT/${namepv##*/}"
-        abort "$unpack_text_3"
+        killtree "$unpack_text_3"
       else
         # unpack dtb, dtbo
         for unp in $(ls -1d * 2>/dev/null | sort -n -t . -k 2); do
@@ -188,7 +188,7 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
         for unsl in $(ls -1 *.[0-9]* 2>/dev/null | sort -n -t . -k 2); do
             echo "Decode: $unsl > dts_$unsl"
             dtc -q -@ -I dtb -O dts -o dts_$unsl $unsl
-            [ "$?" != 0 ] && abort "$unpack_text_5 $unsl"
+            [ "$?" != 0 ] && killtree "$unpack_text_5 $unsl"
             mv $unsl cache/$unsl
             sha256sum -b dts_$unsl > cache/md5_$unsl
         done
@@ -199,7 +199,7 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
         cd "${vch%.*}"
         EXTRACT_UNSAFE_SYMLINKS=1 cpio -d -F "$OUTPUT/${namepv##*/}/$vch" -i 2>&1
         if [ "$?" != 0 -o ! "$(ls)" ];then
-          abort "$unpack_text_4"
+          killtree "$unpack_text_4"
         else
         rm -f "$OUTPUT/${namepv##*/}/$vch"
         fi
@@ -216,7 +216,7 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
       for dtbo in $(ls -t dtb.* | sort -n -t . -k 2);do
         echo "Decode: $dtbo"
         dtc -q -@ -I dtb -O dts -o dts.${dtbo##*.} $dtbo
-        [ "$?" != 0 ] && abort "$unpack_text_5 $dtbo"
+        [ "$?" != 0 ] && killtree "$unpack_text_5 $dtbo"
         mv $dtbo cache/$dtbo
         sha256sum -b dts.${dtbo##*.} > cache/md5_dts.${dtbo##*.}
       done
@@ -225,13 +225,17 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
     rm -fr "$OUTPUT/${namepv##*/}"
     echo -e "$unpack_text_8 ${file_img##*/} ($dang_file)\n" >&2
     fi
+    [ -d "$OUTPUT/${namepv##*/}" ] && echo -e "$save_text $OUTPUT/${namepv##*/}\n"
 else
     if [ "$dang_file" == "super" ];then
     echo -e "$unpack_text_7\n"
     [ "$dang_tep" == 'amlogic' ] && echo -e "$save_text ${INPUT%/*}/${ten_paion}_amlogic\n" || echo -e "$save_text $INPUT\n"
     fi
-echo -e "$unpack_text_6 ${file_img##*/} ($dang_file)\n"
-[ "$NODECO" == 1 ] && mv "$file_img" "$PTSD/out/${file_img##*/}"
+    echo -e "$unpack_text_6 ${file_img##*/} ($dang_file)\n"
+    if [ "$NODECO" == 1 ];then
+    echo -e "$save_text $PTSD/out\n"
+    mv "$file_img" "$PTSD/out/${file_img##*/}"
+    fi
 fi
 
 if [ "$XOAOAT" == 1 ];then
