Upload file

diff --git a/pio/src/main/assets/home/bin/repack_img b/pio/src/main/assets/home/bin/repack_img
--- a/pio/src/main/assets/home/bin/repack_img
+++ b/pio/src/main/assets/home/bin/repack_img
@@ -84,14 +84,22 @@ saved="$OUTPUT/out/${INPUT##*/}.img"
 info_size="${INPUT%/*}/config/${INPUT##*/}_size.txt"
 kernel_dts_md5="${INPUT%/*}/config/${INPUT##*/}_kernel_dts_md5.txt"
 dts_md5="${INPUT%/*}/config/${INPUT##*/}_dts_md5.txt"
+lvnen="$(glog nen_br 8)"
+info_type="$(cat "$info" 2>/dev/null)"
 export MKE2FS_CONFIG="$ETC/mke2fs.conf"
 
-if [[ "$(cat $info)" =~ ^(vendor_boot|logo|squashfs|boot|vbmeta|vbmeta_system|dtbo)$ ]];then
+# Ép build mặc định đối với định dạng sau
+if [[ "$info_type" =~ ^(vendor_boot|logo|squashfs|boot|vbmeta|vbmeta_system|dtbo)$ ]];then
 TTBUILDI=0
 CONVER='raw'
 fi
 
 [ -f "$saved" ] && rm -fr "$saved"
+
+if [ "$CONVER" != "raw" ];then
+saved="$TMP/${saved##*/}"
+out_saved="$saved"
+fi
 
 # Chọn định dạng tệp phân vùng
 if [ "$TTBUILDI" == 1 ];then
@@ -103,7 +111,7 @@ elif [ "$TTBUILDI" == 4 ] || [ "$TTBUILDI" == 5 ];then
 partition='f2fs'
 [ "$TTBUILDI" == 5 ] && f2fsrw=1
 else
-partition="$(cat $info)"
+partition="$info_type"
 fi
 
 if [ "$NENEROFS" == "lz4" ];then
@@ -117,7 +125,7 @@ else
 fi
 
 [ -e "$OUTPUT/out" ] || mkdir -p "$OUTPUT/out"
-echo -e "$build_text: ${INPUT##*/} ($partition) ➠ ($CONVER)...\n"
+echo -e "$replag_text_2: ${INPUT##*/} ($partition) ➠ (raw)...\n"
 
 # patch fstab
 if [ "$AVBIMG" == 1 ];then
@@ -125,17 +133,17 @@ rm -fr $INPUT/bin/install-recovery.sh $INPUT/etc/init/vendor_flash_recovery.rc $
 listfab="$(find "$INPUT" -type f -name "fstab*" 2>/dev/null)"
 for fstab in $listfab; do
    if [ -f "$fstab" ];then
-     if [ "$2" == 1 ];then
-       if [[ -n $(cat "$fstab" | grep -v "avb_keys=/avb/q-gsi.avbpubkey:/avb/r-gsi.avbpubkey:/avb/s-gsi.avbpubkey" | grep -i "avb") ]]; then
-         sed -i "s/avb,//g; s/,avb=.*system//g; s/,avb=.*vendor//g; s/,avb=.*vbmeta//g; s/,avb_keys.*key//g; s/,avb=vbmeta//g; s/,avb//g; s/,,/,/g" "$fstab"
-         echo "Deleted avb in fstab: ${fstab##*/}"
+       if [ "$2" == 1 ];then
+           if [[ -n $(cat "$fstab" | grep -v "avb_keys=/avb/q-gsi.avbpubkey:/avb/r-gsi.avbpubkey:/avb/s-gsi.avbpubkey" | grep -i "avb") ]]; then
+           sed -i "s/avb,//g; s/,avb=.*system//g; s/,avb=.*vendor//g; s/,avb=.*vbmeta//g; s/,avb_keys.*key//g; s/,avb=vbmeta//g; s/,avb//g; s/,,/,/g" "$fstab"
+           echo "Deleted avb in fstab: ${fstab##*/}"
+           fi
+           if [[ -n $(cat "$fstab" | egrep -i "fileencryption|keydirectory|metadata_encryption") ]]; then
+           sed -i -e 's/fileencryption=[^,]*,//' -e 's/keydirectory=[^,]*,//' -e 's/metadata_encryption=[^,]*,//' "$fstab"
+           sed -i "s/,fileencryption=.*_v0//g; s/,fileencryption=.*v2//g; s/,metadata_encryption=.*_v0//g; s/,metadata_encryption=.*xts//g; s/,fileencryption=.*xts//g; s/,fileencryption=ice//g; s/fileencryption/encryptable/g" "$fstab"
+           echo "Decrypted data: ${fstab##*/}"
+           fi
        fi
-       if [[ -n $(cat "$fstab" | egrep -i "fileencryption|keydirectory|metadata_encryption") ]]; then
-         sed -i -e 's/fileencryption=[^,]*,//' -e 's/keydirectory=[^,]*,//' -e 's/metadata_encryption=[^,]*,//' "$fstab"
-         sed -i "s/,fileencryption=.*_v0//g; s/,fileencryption=.*v2//g; s/,metadata_encryption=.*_v0//g; s/,metadata_encryption=.*xts//g; s/,fileencryption=.*xts//g; s/,fileencryption=ice//g; s/fileencryption/encryptable/g" "$fstab"
-         echo "Decrypted data: ${fstab##*/}"
-       fi
-     fi
    fi
 done
 fi
@@ -214,31 +222,31 @@ elif [ "$partition" = "boot" ] || [ "$partition" = "vendor_boot" ]; then
     magiskboot repack "${INPUT##*/}.img" "$saved" 2>&1
     echo
 elif [ "$partition" = "vbmeta_system" ] || [ "$partition" = "vbmeta" ]; then
-  cd $INPUT
-  if [ "$AVBIMG" == 1 ];then
-  magiskboot hexpatch ${INPUT##*/}.img 0000000000000000617662746F6F6C20 0000000200000000617662746F6F6C20
-  fi
-  cp -rf "${INPUT##*/}.img" "$saved"
-elif [ "$partition" = "logo" ];then
-  logo_dumper.py --out "$INPUT/new-logo.img" --bmpdir "$INPUT" "$INPUT/logo.img" repack
-  mv -f "$INPUT/new-logo.img" "$saved"
-  echo
-elif [ "$partition" = "dtbo" ];then
-  cd "$INPUT"
-  for dtbo in $(ls -1d dts.* | sort -n -t . -k 2); do
-    if [ "$(checksum $dtbo)" == "$(cat cache/md5_$dtbo 2>/dev/null)" ];then
-    echo "Copy raw: dtb.${dtbo##*.}"
-    cp -f cache/dtb.${dtbo##*.} dtb.${dtbo##*.}
-    else
-    echo "Build dtb: $dtbo"
-    dtc -q -I dts -O dtb -@ -o dtb.${dtbo##*.} $dtbo
-    [ "$?" != 0 ] && killtree "Error: Build dtb"
+    cd $INPUT
+    if [ "$AVBIMG" == 1 ];then
+    magiskboot hexpatch ${INPUT##*/}.img 0000000000000000617662746F6F6C20 0000000200000000617662746F6F6C20
     fi
-  done
-  dtbo create dtbo.img $(ls -1d dtb.* | sort -n -t . -k 2) >/dev/null
-  rm -fr dtb.*
-  cp -f dtbo.img "$saved"
-  echo
+    cp -rf "${INPUT##*/}.img" "$saved"
+elif [ "$partition" = "logo" ];then
+    logo_dumper.py --out "$INPUT/new-logo.img" --bmpdir "$INPUT" "$INPUT/logo.img" repack
+    mv -f "$INPUT/new-logo.img" "$saved"
+    echo
+elif [ "$partition" = "dtbo" ];then
+    cd "$INPUT"
+    for dtbo in $(ls -1d dts.* | sort -n -t . -k 2); do
+        if [ "$(checksum $dtbo)" == "$(cat cache/md5_$dtbo 2>/dev/null)" ];then
+        echo "Copy raw: dtb.${dtbo##*.}"
+        cp -f cache/dtb.${dtbo##*.} dtb.${dtbo##*.}
+        else
+        echo "Build dtb: $dtbo"
+        dtc -q -I dts -O dtb -@ -o dtb.${dtbo##*.} $dtbo
+        [ "$?" != 0 ] && killtree "Error: Build dtb"
+        fi
+    done
+    dtbo create dtbo.img $(ls -1d dtb.* | sort -n -t . -k 2) >/dev/null
+    rm -fr dtb.*
+    cp -f dtbo.img "$saved"
+    echo
 elif [ "$partition" == "squashfs" ];then
     [ "$ROT" == 0 ] && killtree "Error build: squashfs, $root_warning_text"
     loai_nen="$(grep '^Compression' "$fs_options" | awk '{print $2}')"
@@ -262,72 +270,72 @@ elif [ "$partition" == "squashfs" ];then
     progress -1/0
     echo
 elif [ "$partition" == "f2fs" ];then
-  [ "$DISATFS" == 0 ] || patch "$INPUT" "$fs_config" "$file_contexts" >$TMP/patch_fs.log
-  if [ -f "$info_size" ] && [ "$(cat $info)" == "f2fs" ] && [ "$TTBUILDI" == 0 ];then
-  size_real=$(cat $info_size 2>/dev/null);
-  size_real="$(echo "$SAINEN * 1024 * 1024 + $size_real" | bc)"
-  else
-  size_orig="$(du -bs "$INPUT" | awk '{ print $1 }')"
-  size_real="$(echo "($SAINEN + 6) * 1024 * 1024 + $size_orig" | bc)"
-  fi
-  truncate -s $size_real "$saved"
-  if [ -f "$INPUT/system/build.prop" ];then
-  mount_dir="/"
-  cp -rf "$fs_config" "${fs_config}_s"
-  cp -rf "$file_contexts" "${file_contexts}_s"
-  fs_config="${fs_config}_s"
-  file_contexts="${file_contexts}_s"
-  sed -i -e "/^${INPUT##*/} 0/d" -e "s|^${INPUT##*/}/|/|" "$fs_config"
-  sed -i -e "/^\/${INPUT##*/} u/d" -e "/^\/${INPUT##*/}\/ u/d" -e "s|^/${INPUT##*/}||" "$file_contexts"
-  else
-  mount_dir="/${INPUT##*/}"
-  fi
-  if [ "$TTBUILDI" == 0 ];then
-  [ "$(cat "$fs_options" 2>/dev/null | grep 'superblock features' | grep -cm1 ro)" == 1 ] && f2fsrw=0 || f2fsrw=1
-  fi
-  if [ "$f2fsrw" == 1 ];then
-  make_f2fs -g android -O compression -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real &>$TMP/make_f2fs.log || killtree "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
-  sload_f2fs -t "$mount_dir" -C "$fs_config" -s "$file_contexts" -T $time_build -f "$INPUT" -c "$saved" 2>&1 | tee $TMP/sload_f2fs.log | sed -e "/Free segments:/d" -e "/Not enough space/d"
-  else
-  make_f2fs -t 0 -g android -O ro -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real &>$TMP/make_f2fs.log || killtree "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
-  sload_f2fs -t "$mount_dir" -C "$fs_config" -s "$file_contexts" -T $time_build -f "$INPUT" "$saved" 2>&1 | tee $TMP/sload_f2fs.log | sed -e "/Free segments:/d" -e "/Not enough space/d"
-  fi
-  [ "$(grep -cm1 'Done:' $TMP/sload_f2fs.log)" == 0 ] && killtree "Error build sload_f2fs, Suggestion: Increase free MB, log: $TMP/sload_f2fs.log" "$saved";
-  [ -f "$INPUT/system/build.prop" ] && rm -f "$file_contexts" "$fs_config"
-  echo
+    [ "$DISATFS" == 0 ] || patch "$INPUT" "$fs_config" "$file_contexts" >$TMP/patch_fs.log
+    if [ -f "$info_size" ] && [ "$info_type" == "f2fs" ] && [ "$TTBUILDI" == 0 ];then
+    size_real=$(cat $info_size 2>/dev/null);
+    size_real="$(echo "$SAINEN * 1024 * 1024 + $size_real" | bc)"
+    else
+    size_orig="$(du -bs "$INPUT" | awk '{ print $1 }')"
+    size_real="$(echo "($SAINEN + 6) * 1024 * 1024 + $size_orig" | bc)"
+    fi
+    truncate -s $size_real "$saved"
+    if [ -f "$INPUT/system/build.prop" ];then
+    mount_dir="/"
+    cp -rf "$fs_config" "${fs_config}_s"
+    cp -rf "$file_contexts" "${file_contexts}_s"
+    fs_config="${fs_config}_s"
+    file_contexts="${file_contexts}_s"
+    sed -i -e "/^${INPUT##*/} 0/d" -e "s|^${INPUT##*/}/|/|" "$fs_config"
+    sed -i -e "/^\/${INPUT##*/} u/d" -e "/^\/${INPUT##*/}\/ u/d" -e "s|^/${INPUT##*/}||" "$file_contexts"
+    else
+    mount_dir="/${INPUT##*/}"
+    fi
+    if [ "$TTBUILDI" == 0 ];then
+    [ "$(cat "$fs_options" 2>/dev/null | grep 'superblock features' | grep -cm1 ro)" == 1 ] && f2fsrw=0 || f2fsrw=1
+    fi
+    if [ "$f2fsrw" == 1 ];then
+    make_f2fs -g android -O compression -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real &>$TMP/make_f2fs.log || killtree "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
+    sload_f2fs -t "$mount_dir" -C "$fs_config" -s "$file_contexts" -T $time_build -f "$INPUT" -c "$saved" 2>&1 | tee $TMP/sload_f2fs.log | sed -e "/Free segments:/d" -e "/Not enough space/d"
+    else
+    make_f2fs -t 0 -g android -O ro -r -w 4096 -l "${INPUT##*/}" -f "$saved" $size_real &>$TMP/make_f2fs.log || killtree "Error build make_f2fs, Suggestion: Increase free MB" "$saved"
+    sload_f2fs -t "$mount_dir" -C "$fs_config" -s "$file_contexts" -T $time_build -f "$INPUT" "$saved" 2>&1 | tee $TMP/sload_f2fs.log | sed -e "/Free segments:/d" -e "/Not enough space/d"
+    fi
+    [ "$(grep -cm1 'Done:' $TMP/sload_f2fs.log)" == 0 ] && killtree "Error build sload_f2fs, Suggestion: Increase free MB, log: $TMP/sload_f2fs.log" "$saved";
+    [ -f "$INPUT/system/build.prop" ] && rm -f "$file_contexts" "$fs_config"
+    echo
 elif [ "$partition" == "ext" ];then
-  [ "$DISATFS" == 0 ] || patch "$INPUT" "$fs_config" "$file_contexts" >$TMP/patch_fs.log
-  size_real=$(cat $info_size 2>/dev/null);
-  size_orig="$(du -sb "$INPUT" | awk '{ print $1 }')"
-  if test "$size_orig" -le "52428800"; then
-  size_orig=209715200
-  else
-  size_orig="$(echo "$size_orig * 1.1" | bc | cut -d. -f1)"
-  fi
-  if [ "$SAINEN" == 0 ] && [ "$(cat $info)" == "ext" ] && [ "$TTBUILDI" == 0 ];then
-    if [ "$e2fsdroid" == 1 ];then
-    size="$(echo "$size_real / 4096" | bc)";
-    mke2fs -O ^has_journal -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "/${INPUT##*/}" "$saved" $size 2>&1
-    e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_ext.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_ext.log" "$saved"
+    [ "$DISATFS" == 0 ] || patch "$INPUT" "$fs_config" "$file_contexts" >$TMP/patch_fs.log
+    size_real=$(cat $info_size 2>/dev/null);
+    size_orig="$(du -sb "$INPUT" | awk '{ print $1 }')"
+    if test "$size_orig" -le "52428800"; then
+    size_orig=209715200
     else
-    make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_real -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" & process_count $size_real "$saved"
-    echo
+    size_orig="$(echo "$size_orig * 1.1" | bc | cut -d. -f1)"
     fi
-  else
-    if [ "$e2fsdroid" == 1 ];then
-    size="$(echo "$size_orig / 4096" | bc)";
-    mke2fs -O ^has_journal -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "/${INPUT##*/}" "$saved" $size 2>&1
-    e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_exts.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_exts.log" "$saved"
+    if [ "$SAINEN" == 0 ] && [ "$info_type" == "ext" ] && [ "$TTBUILDI" == 0 ];then
+        if [ "$e2fsdroid" == 1 ];then
+        size="$(echo "$size_real / 4096" | bc)";
+        mke2fs -O ^has_journal -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "/${INPUT##*/}" "$saved" $size 2>&1
+        e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_ext.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_ext.log" "$saved"
+        else
+        make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_real -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" & process_count $size_real "$saved"
+        echo
+        fi
     else
-    make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_orig -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" & process_count $size_orig "$saved"
-    echo
+        if [ "$e2fsdroid" == 1 ];then
+        size="$(echo "$size_orig / 4096" | bc)";
+        mke2fs -O ^has_journal -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "/${INPUT##*/}" "$saved" $size 2>&1
+        e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_exts.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_exts.log" "$saved"
+        else
+        make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_orig -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" & process_count $size_orig "$saved"
+        echo
+        fi
+        resize2fs -M "$saved" 2>&1
+        if [[ "$SAINEN" != 0 ]];then
+        kichthuoc="$(resize2fs -P "$saved" 2>/dev/null | grep -o '[0-9]*')"
+        resize2fs -f "$saved" $(echo "$SAINEN * 1024 / 4 + $kichthuoc" | bc) 2>&1
+        fi
     fi
-    resize2fs -M "$saved" 2>&1
-    if [[ "$SAINEN" != 0 ]];then
-    kichthuoc="$(resize2fs -P "$saved" 2>/dev/null | grep -o '[0-9]*')"
-    resize2fs -f "$saved" $(echo "$SAINEN * 1024 / 4 + $kichthuoc" | bc) 2>&1
-    fi
-  fi
 fi
 
 if [[ -f $OUTPUT/dynamic_partitions_op_list ]] && [[ "$partition" =~ ^(ext|f2fs|erofs)$ ]];then
@@ -340,27 +348,42 @@ if [[ -f $OUTPUT/dynamic_partitions_op_list ]] && [[ "$partition" =~ ^(ext|f2fs|
     fi
 fi
 
-lvnen="$(glog nen_br 8)";
 if [[ "$partition" =~ ^(erofs|f2fs|ext)$ ]];then
     text_sizes=$(wc -c <"$saved")
     echo "$sizes_text: ${saved##*/} $(coverbyte $text_sizes) ($text_sizes)"
     echo
+    if [ "$CONVER" != "raw" ];then
+    echo -e "$unpack_text_0 ${INPUT##*/} ($partition) ➠ ($CONVER)..."
+    echo
+    fi
     if [ "$CONVER" == 'zstd' ] || [ "$CONVER" == 'gz' ] || [ "$CONVER" == 'xz' ] || [ "$CONVER" == 'lz4' ] || [ "$CONVER" == 'lzma' ];then
-    zstd -f -$lvnen -T$threads --format=$CONVER --compress "$saved" -o "${saved%.*}.img.$CONVER" &>/dev/null
-    [ "$?" == 0 ] && rm -f "$saved"
+    zstd --progress -f -$lvnen -T$threads --format=$CONVER --compress "$saved" -o "${out_saved%.*}.img.$CONVER" &>"$TMP/repzstd.log" &
+    PIDK=$!
+    while kill -0 $PIDK 2>/dev/null; do
+        if [ -f "$TMP/repzstd.log" ];then
+            num2="$(tr '\r' '\n' < "$TMP/repzstd.log" | awk '/Read:/{r=$2*($3=="GiB"?1024:1); t=$5*($6=="GiB"?1024:1)} END{print (t>0?int(r/t*100):0)}')"
+            if [ "$num2" ];then
+            [ "${num2:-0}" == "${num4:-1}" ] || progress "$num2/100"
+            num4="$num2"
+            fi
+        fi
+    sleep 1
+    done
+    progress -1/0
     elif [ "$CONVER" == 'dat' ] || [ "$CONVER" == 'br' ];then
-    img2simg $saved >/dev/null
-    img2sdat "$saved" -o "$OUTPUT/out" -v 4 -p ${INPUT##*/} &>/dev/null
+    img2simg "$saved" >/dev/null
+    img2sdat "$saved" -o "$OUTPUT/out" -v 4 -p "${INPUT##*/}" &>/dev/null
     [ "$?" == 0 ] && rm -f "$saved"
     [ -f "$OUTPUT/out/${INPUT##*/}.new.dat" ] || killtree "Error creating file ${INPUT##*/}.new.dat failed !!!"
-    if [ "$CONVER" == 'br' ];then
-    LEVEL="$(echo "$lvnen / 2" | bc)"
-    brotli -fq "$LEVEL" "$OUTPUT/out/${INPUT##*/}.new.dat" -o "$OUTPUT/out/${INPUT##*/}.new.dat.br" >/dev/null
-    [ "$?" == 0 ] && rm -f "$OUTPUT/out/${INPUT##*/}.new.dat"
-    fi
+        if [ "$CONVER" == 'br' ];then
+        LEVEL="$(echo "$lvnen / 2" | bc)"
+        brotli -fq "$LEVEL" "$OUTPUT/out/${INPUT##*/}.new.dat" -o "$OUTPUT/out/${INPUT##*/}.new.dat.br" >/dev/null
+        [ "$?" == 0 ] && rm -f "$OUTPUT/out/${INPUT##*/}.new.dat"
+        fi
     elif [ "$CONVER" == 'sparse' ];then
-    img2simg "$saved" >/dev/null
+    img2simg "$saved" "$out_saved" >/dev/null
     fi
+    [ "$CONVER" != "raw" ] && rm -f "$saved"
 fi
 
 if [ "$CDELIMG" == 1 ];then
diff --git a/pio/src/main/assets/home/bin/unpack_img b/pio/src/main/assets/home/bin/unpack_img
--- a/pio/src/main/assets/home/bin/unpack_img
+++ b/pio/src/main/assets/home/bin/unpack_img
@@ -53,20 +53,31 @@ fi
 source language 2>/dev/null
 dang_tep="$(checktype "$INPUT")"
 
+process_count(){
+PIDK=$!
+num1="$1"; num2="$2";
+while kill -0 $PIDK 2>/dev/null; do
+if [ -f "$num2" ];then
+    num3=$(tr '\r' '\n' < "$num2" | awk '/ : /{v=$3} END{print v}')
+    if [ "$num3" ];then
+    [ "${num3:-0}" == "${num4:-1}" ] || progress "$((num3 * 100 / num1))/100"
+    num4="$num3"
+    fi
+fi
+sleep 1
+done
+progress -1/0
+}
+
 # xử lý zip
 if [ "$dang_tep" == 'zip' ];then
 xacnhatpay="$(listpayload "$INPUT")"
-xoazip=1
     if [ -z "$xacnhatpay" ];then
     echo -e "$unpack_text_1 $PVUGBIN...\n"
+    xoazip=1
     tenpjag="$(echo "${PVUGBIN##*/}")"
-#    if [ "${tenpjag##*.}" == "zstd" ] || [ "${tenpjag##*.}" == "zst" ];then
-#    unzip -qop "$INPUT" $PVUGBIN | zstd -c -d > "$TMP/${tenpjag%%.*}.img"
-#    INPUT="$TMP/${tenpjag%%.*}.img";
-#    else
     unzip -qo "$INPUT" $PVUGBIN ${PVUGBIN%/*}/${tenpjag%%.*}.transfer.list ${tenpjag%%.*}.transfer.list -d $TMP 2>/dev/null
     INPUT="$TMP/$PVUGBIN";
-#    fi
     dang_tep="$(checktype "$INPUT")"
         if [ "$dang_tep" == 'super' ];then
         echo -e "$unpack_text_7\n" >&2
@@ -77,41 +88,41 @@ xoazip=1
 fi
 
 if [ "$dang_tep" == 'zstd' ];then
-  echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
-  file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
-  zstd -T$threads -f -d -k "$INPUT" -o "$file_img" &>/dev/null
-  rm -f "$INPUT"
+    echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
+    file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
+    size_zstd="$(zstd -lv "$INPUT" 2>/dev/null | awk -F'[()]' '/Decompressed Size/ {print $2}' | awk '{print $1}')"
+    zstd -T$threads --progress -vv -f -d -k "$INPUT" -o "$file_img" &>"$TMP/unzstd.log" & process_count "$size_zstd" "$TMP/unzstd.log"
 elif [ "$dang_tep" == 'br' ] || [ "$dang_tep" == 'dat' ];then
-  tenpjanvung="$(echo "${INPUT##*/}" | cut -d. -f1)"
-  [ -e "${INPUT%/*}/$tenpjanvung.transfer.list" ] || killtree "$more_text_5 $tenpjanvung.transfer.list"
-  echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
-  [ "${INPUT##*.}" == 'br' ] && brotli -f -d "$INPUT" -o "$TMP/$(echo "${INPUT%.*}" | awk -F/ '{print $NF}')" &>/dev/null
-  file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
-  sdat2img "${INPUT%/*}/$tenpjanvung.transfer.list" "$TMP/$(echo "${INPUT%.*}" | awk -F/ '{print $NF}')" "$file_img" &>/dev/null
+    tenpjanvung="$(echo "${INPUT##*/}" | cut -d. -f1)"
+    [ -e "${INPUT%/*}/$tenpjanvung.transfer.list" ] || killtree "$more_text_5 $tenpjanvung.transfer.list"
+    echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
+    [ "${INPUT##*.}" == 'br' ] && brotli -f -d "$INPUT" -o "$TMP/$(echo "${INPUT%.*}" | awk -F/ '{print $NF}')" &>/dev/null
+    file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
+    sdat2img "${INPUT%/*}/$tenpjanvung.transfer.list" "$TMP/$(echo "${INPUT%.*}" | awk -F/ '{print $NF}')" "$file_img" &>/dev/null
 elif [ "$dang_tep" == 'sparse' ];then
-  echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
-  file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
-  simg2img "$INPUT" "$file_img"
+    echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
+    file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
+    simg2img "$INPUT" "$file_img"
 elif [ "$dang_tep" == 'payload' ] || [ -n "$xacnhatpay" ];then
-  echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
-  payload_dumper --no-parallel --out "$TMP" --images "$PVUGBIN" "$INPUT" >/dev/null || killtree "Payload unpack error"
-  file_img="$TMP/$PVUGBIN.img"
+    echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
+    payload_dumper --no-parallel --out "$TMP" --images "$PVUGBIN" "$INPUT" >/dev/null || killtree "Payload unpack error"
+    file_img="$TMP/$PVUGBIN.img"
 elif [ "$dang_tep" == 'super' ];then
-  echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
-  lpunpack -p "$PVUGBIN" "$INPUT" "$TMP" >/dev/null
-  file_img="$TMP/$(echo $PVUGBIN).img"
+    echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
+    lpunpack -p "$PVUGBIN" "$INPUT" "$TMP" >/dev/null
+    file_img="$TMP/$(echo $PVUGBIN).img"
 elif [ "$dang_tep" == 'amlogic' ];then
-  echo -e "$unpack_text_1 (${INPUT##*/}) ➠ (unpack)...\n"
-  ten_paion="$(echo "${INPUT##*/}" | cut -d. -f1)"
-  ampack unpack "$INPUT" "${INPUT%/*}/${ten_paion}_amlogic" >$TMP/ampack_unpack.log && sed -i $'s/\033\\[[0-9;]*m//g' "$TMP/ampack_unpack.log"
-  for vck in ${INPUT%/*}/${ten_paion}_amlogic/*.PARTITION; do
-  echo "mv: ${vck##*/} ➠ $(echo "${vck##*/}" | sed 's|\.PARTITION$|\.img|')"
-  mv "$vck" "${vck%.*}.img"
-  done
-  echo
-  file_img="${INPUT%/*}/${ten_paion}_amlogic/super.img"
+    echo -e "$unpack_text_1 (${INPUT##*/}) ➠ (unpack)...\n"
+    ten_paion="$(echo "${INPUT##*/}" | cut -d. -f1)"
+    ampack unpack "$INPUT" "${INPUT%/*}/${ten_paion}_amlogic" >$TMP/ampack_unpack.log && sed -i $'s/\033\\[[0-9;]*m//g' "$TMP/ampack_unpack.log"
+    for vck in ${INPUT%/*}/${ten_paion}_amlogic/*.PARTITION; do
+    echo "mv: ${vck##*/} ➠ $(echo "${vck##*/}" | sed 's|\.PARTITION$|\.img|')"
+    mv "$vck" "${vck%.*}.img"
+    done
+    echo
+    file_img="${INPUT%/*}/${ten_paion}_amlogic/super.img"
 else
-  file_img="$INPUT"
+    file_img="$INPUT"
 fi
 
 # phòng hờ
@@ -120,10 +131,6 @@ simg2img "$file_img" >$TMP/simg2img.log
 fi
 
 dang_file="$(checktype "$file_img")"
-if [ "$NODECO" != 1 ] && [ -f "$file_img" ] && [ "$dang_file" != "unknow" ] && [ "$dang_file" != "super" ];then
-
-echo -e "$decompile_text: ${file_img##*/} ($dang_file)...\n"
-
 namepv="${file_img%.*}"
 in_name="$OUTPUT/${namepv##*/}"
 info="$OUTPUT/config/${namepv##*/}_info"
@@ -132,71 +139,72 @@ file_contexts="$OUTPUT/config/${namepv##*/}_file_contexts"
 fs_options="$OUTPUT/config/${namepv##*/}_fs_options"
 info_size="$OUTPUT/config/${namepv##*/}_size.txt"
 
-# dọn dẹp trước khi tạo
-rm -fr "$in_name"
+if [ "$NODECO" != 1 ] && [ -f "$file_img" ] && [ "$dang_file" != "unknow" ] && [ "$dang_file" != "super" ];then
+
+echo -e "$decompile_text: ${file_img##*/} ($dang_file)...\n"
+# xoá cũ
+[ -d "$in_name" ] && rm -fr "$in_name" "$info" "$file_contexts" "$fs_config" "$fs_options" "$info_size" "$OUTPUT/config/exception.log"
+# tạo thư mục
 mkdir -p "$in_name" $OUTPUT/config
 
-# xoá cũ
-[ -d "$in_name" ] && rm -fr "$info" "$file_contexts" "$fs_config" "$fs_options" "$info_size" "$OUTPUT/config/exception.log"
-
     if [ "$dang_file" == 'ext' ];then
-      imgextractor "$file_img" "$OUTPUT" >$TMP/imgextractor_ext.log
-      echo "$dang_file" > "$info"
+        imgextractor "$file_img" "$OUTPUT" >$TMP/imgextractor_ext.log
+        echo "$dang_file" > "$info"
     elif [ "$dang_file" == 'f2fs' ];then
-      extract.f2fs "$file_img" "$OUTPUT" &>$TMP/unpack_f2fs.log || killtree "Extracting f2fs failed, check log: $TMP/unpack_f2fs.log";
-      if [ -f "$fs_config" ];then
-      luu_contexts="$(sed -e "s|s0/|s0\n/|g" "$file_contexts" | sort)"
-      luu_config="$(cat "$fs_config" | awk '{print "'${namepv##*/}'"$0}' | sort | sed -e "s|^${namepv##*/}/ 0 2000 0755|${namepv##*/}/ 0 0 0755|" -e "s|^${namepv##*/} 0 0 0755|/ 0 0 0755|")"
-          if [ -f "$in_name/system/build.prop" ];then
-          luu_contexts="$(echo "$luu_contexts" | sed -e "s|^/${namepv##*/} u|/${namepv##*/}/ u|")"
-          fi
-      echo "$luu_config" > "$fs_config"
-      echo "$luu_contexts" > "$file_contexts"
-      fi
-      echo "$(stat -c%s "$file_img")" > "$info_size"
-      echo "$dang_file" > "$info"
-      fsck.f2fs "$file_img" &> "$fs_options"
+        extract.f2fs "$file_img" "$OUTPUT" &>$TMP/unpack_f2fs.log || killtree "Extracting f2fs failed, check log: $TMP/unpack_f2fs.log";
+        if [ -f "$fs_config" ];then
+        luu_contexts="$(sed -e "s|s0/|s0\n/|g" "$file_contexts" | sort)"
+        luu_config="$(cat "$fs_config" | awk '{print "'${namepv##*/}'"$0}' | sort | sed -e "s|^${namepv##*/}/ 0 2000 0755|${namepv##*/}/ 0 0 0755|" -e "s|^${namepv##*/} 0 0 0755|/ 0 0 0755|")"
+        if [ -f "$in_name/system/build.prop" ];then
+        luu_contexts="$(echo "$luu_contexts" | sed -e "s|^/${namepv##*/} u|/${namepv##*/}/ u|")"
+        fi
+        echo "$luu_config" > "$fs_config"
+        echo "$luu_contexts" > "$file_contexts"
+        fi
+        echo "$(stat -c%s "$file_img")" > "$info_size"
+        echo "$dang_file" > "$info"
+        fsck.f2fs "$file_img" &> "$fs_options"
     elif [ "$dang_file" == 'erofs' ];then
-      extract.erofs -T$threads -x -i "$file_img" -o "$OUTPUT" >$TMP/extract_erofs.log || killtree "\nextract.erofs error: ${namepv##*/}" "$in_name" &
-      PIDK=$!
-      while kill -0 $PIDK 2>/dev/null; do
-      if [ -f $TMP/extract_erofs.log ];then
-      number_kk="$(sed -E 's/\x1b\[[0-9;]*m//g; s/[\r\t]/\n/g' "$TMP/extract_erofs.log" | grep -E 'Extract: \[[^]]+\]' | tail -n 1 | awk '{print $3}' | cut -d\. -f1)"
-          if [ "$number_kk" ];then
-          [ "${number_kk:-0}" == "${save_num:-1}" ] || progress $number_kk/100
-          save_num="$number_kk"
-          fi
-      fi
-      sleep 1
-      done
-      progress -1/0
-      [ -f $TMP/extract_erofs.log ] && sed -i 's/\x1b\[[^m]*m//g' $TMP/extract_erofs.log
-      echo "$dang_file" > "$info"
-      if [ -f $OUTPUT/config/exception.log ];then
-      rm -fr "$in_name"
-      cat $OUTPUT/config/exception.log >&2
-      killtree "\nIncomplete file error please check hash" $OUTPUT/config/exception.log
-      fi
+        extract.erofs -T$threads -x -i "$file_img" -o "$OUTPUT" >$TMP/extract_erofs.log || killtree "\nextract.erofs error: ${namepv##*/}" "$in_name" &
+        PIDK=$!
+        while kill -0 $PIDK 2>/dev/null; do
+        if [ -f $TMP/extract_erofs.log ];then
+        number_kk="$(sed -E 's/\x1b\[[0-9;]*m//g; s/[\r\t]/\n/g' "$TMP/extract_erofs.log" | grep -E 'Extract: \[[^]]+\]' | tail -n 1 | awk '{print $3}' | cut -d\. -f1)"
+            if [ "$number_kk" ];then
+            [ "${number_kk:-0}" == "${save_num:-1}" ] || progress $number_kk/100
+            save_num="$number_kk"
+            fi
+        fi
+        sleep 1
+        done
+        progress -1/0
+        [ -f $TMP/extract_erofs.log ] && sed -i 's/\x1b\[[^m]*m//g' $TMP/extract_erofs.log
+        echo "$dang_file" > "$info"
+        if [ -f $OUTPUT/config/exception.log ];then
+        rm -fr "$in_name"
+        cat $OUTPUT/config/exception.log >&2
+        killtree "\nIncomplete file error please check hash" $OUTPUT/config/exception.log
+        fi
     elif [ "$dang_file" == 'logo' ];then
-    logo_dumper.py --out "$in_name" "$file_img" unpack
-    echo "$dang_file" > "$info"
-    cp -f "$file_img" "$in_name/logo.img"
-    echo
+        logo_dumper.py --out "$in_name" "$file_img" unpack
+        echo "$dang_file" > "$info"
+        cp -f "$file_img" "$in_name/logo.img"
+        echo
     elif [ "$dang_file" == 'vbmeta' ] || [ "$dang_file" == 'vbmeta_system' ];then
-      cp -f "$file_img" "$in_name"
-      echo "$dang_file" > $info
+        cp -f "$file_img" "$in_name"
+        echo "$dang_file" > $info
     elif [ "$dang_file" == 'boot' ] || [ "$dang_file" == 'vendor_boot' ];then
-      cd "$in_name"
-      cp -f "$file_img" "$in_name"
-      magiskboot unpack -h "$file_img" 2>&1
-      if [ "$?" = '1' ];then
-        rm -rf "$in_name"
-        killtree "$unpack_text_3"
-      else
+        cd "$in_name"
+        cp -f "$file_img" "$in_name"
+        magiskboot unpack -h "$file_img" 2>&1
+        if [ "$?" = '1' ];then
+            rm -rf "$in_name"
+            killtree "$unpack_text_3"
+        else
         # unpack dtb, dtbo
         for unp in $(ls -1d * 2>/dev/null | sort -n -t . -k 2); do
-          type_unp="$(checktype $unp)"
-          if [ -f $unp ];then
+        type_unp="$(checktype $unp)"
+        if [ -f $unp ];then
             if [ "$type_unp" == 'dtb' ] || [ "$type_unp" == 'dtbo' ];then
             mkdir -p cache
             echo "$type_unp" > cache/type_$unp
@@ -204,14 +212,14 @@ mkdir -p "$in_name" $OUTPUT/config
             [ "$type_unp" == 'dtbo' ] && dtbo dump $unp -b $unp >$TMP/dtbo_boot.log
             rm $unp
             fi
-          fi
+        fi
         done
         for unsl in $(ls -1 *.[0-9]* 2>/dev/null | sort -n -t . -k 2); do
-            echo "Decode: $unsl > dts_$unsl"
-            dtc -q -@ -I dtb -O dts -o dts_$unsl $unsl
-            [ "$?" != 0 ] && killtree "$unpack_text_5 $unsl"
-            mv $unsl cache/$unsl
-            checksum dts_$unsl > cache/md5_$unsl
+        echo "Decode: $unsl > dts_$unsl"
+        dtc -q -@ -I dtb -O dts -o dts_$unsl $unsl
+        [ "$?" != 0 ] && killtree "$unpack_text_5 $unsl"
+        mv $unsl cache/$unsl
+        checksum dts_$unsl > cache/md5_$unsl
         done
         # unpack cpio
         for vch in $(ls -1d *.cpio vendor_ramdisk/*.cpio 2>/dev/null); do
@@ -220,15 +228,15 @@ mkdir -p "$in_name" $OUTPUT/config
         cd "${vch%.*}"
         EXTRACT_UNSAFE_SYMLINKS=1 cpio -d -F "$in_name/$vch" -i 2>&1
         if [ "$?" != 0 -o ! "$(ls)" ];then
-          killtree "$unpack_text_4"
+        killtree "$unpack_text_4"
         else
         rm -f "$in_name/$vch"
         fi
         cd "$in_name"
         done
-      echo "$dang_file" > $info
-      echo
-      fi
+        echo "$dang_file" > $info
+        echo
+        fi
     elif [ "$dang_file" == 'dtbo' ];then
         echo "$dang_file" > $info
         cd "$in_name"
@@ -250,10 +258,10 @@ mkdir -p "$in_name" $OUTPUT/config
         while kill -0 $PIDK 2>/dev/null; do
         if [ -f $TMP/unsquashfs.log ];then
         number_kk="$(sed 's/[\r\t]/\n/g' $TMP/unsquashfs.log | sed -n 's/.* \([0-9]\+\)%$/\1/p' | tail -n 1)"
-          if [ "$number_kk" ];then
-          [ "${number_kk:-0}" == "${save_num:-1}" ] || progress $number_kk/100
-          save_num="$number_kk"
-          fi
+            if [ "$number_kk" ];then
+            [ "${number_kk:-0}" == "${save_num:-1}" ] || progress $number_kk/100
+            save_num="$number_kk"
+            fi
         fi
         sleep 1
         done
@@ -292,7 +300,7 @@ find "$in_name" -type f -name "*.vdex" -delete
 fi
 
 if [[ "$dang_tep" =~ ^(sparse|zstd|dat|br|payload|super|zip)$ ]];then
-    [ "$xoazip" == 1 ] && rm -f "$TMP/*.transfer.list"
+    [ "$xoazip" == 1 ] && rm -rf "$INPUT" "$TMP/*.transfer.list"
     if [ "$NODECO" != 1 ];then
     [ -f "$file_img" ] && rm -f "$file_img"
     [ "$dang_tep" == "br" ] && rm -f "${file_img%.*}.new.dat"
