Upload file

diff --git a/pio/src/main/assets/home/bin/repack_img b/pio/src/main/assets/home/bin/repack_img
--- a/pio/src/main/assets/home/bin/repack_img
+++ b/pio/src/main/assets/home/bin/repack_img
@@ -1,8 +1,9 @@
 #!/data/data/com.tool.tree/files/home/bin/bash
 shopt -s extglob
+set -o pipefail
 #set -x
 source language 2>/dev/null
-threads=$(nproc)
+#threads=$(nproc)
 show_help() {
   echo "Usage: repack_img -i <input> -o <output> <flags>"
   echo
@@ -166,7 +167,7 @@ progress -1/0
 
 if [ "$partition" == "erofs" ];then
     [ "$DISATFS" == 0 ] || patch "$INPUT" "$fs_config" "$file_contexts" >$TMP/patch_fs.log
-    mkfs.erofs -T $time_build --workers=$threads -z${NENEROFS}${zlsize} --mount-point="/${INPUT##*/}" --fs-config-file="$fs_config" --file-contexts="$file_contexts" "$saved" "$INPUT" &>$TMP/mkfs_erofs.log || killtree "Error build process mkfs.erofs, log: $TMP/mkfs_erofs.log" "$saved" &
+    mkfs.erofs -T $time_build -z${NENEROFS}${zlsize} --mount-point="/${INPUT##*/}" --fs-config-file="$fs_config" --file-contexts="$file_contexts" "$saved" "$INPUT" &>$TMP/mkfs_erofs.log || killtree "Error build process mkfs.erofs, log: $TMP/mkfs_erofs.log" "$saved" &
     PIDK=$!
     while kill -0 $PIDK 2>/dev/null; do
     if [ -f "$TMP/mkfs_erofs.log" ];then
@@ -318,7 +319,8 @@ elif [ "$partition" == "ext" ];then
         mke2fs -O ^has_journal -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "/${INPUT##*/}" "$saved" $size 2>&1
         e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_ext.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_ext.log" "$saved"
         else
-        make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_real -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" & process_count $size_real "$saved"
+        make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_real -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" &
+        process_count $size_real "$saved"
         echo
         fi
     else
@@ -327,7 +329,8 @@ elif [ "$partition" == "ext" ];then
         mke2fs -O ^has_journal -t ext4 -m 0 -b 4096 -I 256 -L "${INPUT##*/}" -M "/${INPUT##*/}" "$saved" $size 2>&1
         e2fsdroid -e -T $time_build -C "$fs_config" -S "$file_contexts" -f "$INPUT" -a "/${INPUT##*/}" "$saved" 2>$TMP/e2fsdroid_exts.log || killtree "Error build process e2fsdroid, log: $TMP/e2fsdroid_exts.log" "$saved"
         else
-        make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_orig -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" & process_count $size_orig "$saved"
+        make_ext4fs -J -T $time_build -L "${INPUT##*/}" -S "$file_contexts" -C "$fs_config" -l $size_orig -a "/${INPUT##*/}" "$saved" "$INPUT" || killtree "Error build process make_ext4fs" "$saved" &
+        process_count $size_orig "$saved"
         echo
         fi
         resize2fs -M "$saved" 2>&1
@@ -357,7 +360,7 @@ if [[ "$partition" =~ ^(erofs|f2fs|ext)$ ]];then
     echo
     fi
     if [ "$CONVER" == 'zstd' ] || [ "$CONVER" == 'gz' ] || [ "$CONVER" == 'xz' ] || [ "$CONVER" == 'lz4' ] || [ "$CONVER" == 'lzma' ];then
-    zstd --progress -f -$lvnen -T$threads --format=$CONVER --compress "$saved" -o "${out_saved%.*}.img.$CONVER" &>"$TMP/repzstd.log" &
+    zstd --progress -f -$lvnen --format=$CONVER --compress "$saved" -o "${out_saved%.*}.img.$CONVER" &>"$TMP/repzstd.log" &
     PIDK=$!
     while kill -0 $PIDK 2>/dev/null; do
         if [ -f "$TMP/repzstd.log" ];then
diff --git a/pio/src/main/assets/home/bin/unpack_img b/pio/src/main/assets/home/bin/unpack_img
--- a/pio/src/main/assets/home/bin/unpack_img
+++ b/pio/src/main/assets/home/bin/unpack_img
@@ -1,7 +1,7 @@
 #!/data/data/com.tool.tree/files/home/bin/bash
 # kakathic
-
-threads=$(nproc)
+set -o pipefail
+#threads=$(nproc)
 show_help() {
   echo "Usage: unpack_img -i <input> -o <output> -p <partition> -n [0/1] -d [0/1]"
   echo
@@ -107,7 +107,8 @@ if [ "$dang_tep" == 'zstd' ];then
     echo -e "$unpack_text_0 (${INPUT##*/}) ➠ (raw)...\n"
     file_img="$TMP/$(echo "${INPUT##*/}" | cut -d. -f1).img"
     size_zstd="$(zstd -lv "$INPUT" 2>/dev/null | awk -F'[()]' '/Decompressed Size/ {print $2}' | awk '{print $1}')"
-    zstd -T$threads --progress -vv -f -d -k "$INPUT" -o "$file_img" &>"$TMP/unzstd.log" & process_count "$size_zstd" "$TMP/unzstd.log"
+    zstd --progress -vv -f -d -k "$INPUT" -o "$file_img" &>"$TMP/unzstd.log" &
+    process_count "$size_zstd" "$TMP/unzstd.log"
 elif [ "$dang_tep" == 'br' ] || [ "$dang_tep" == 'dat' ];then
     tenpjanvung="$(echo "${INPUT##*/}" | cut -d. -f1)"
     [ -e "${INPUT%/*}/$tenpjanvung.transfer.list" ] || killtree "$more_text_5 $tenpjanvung.transfer.list"
@@ -121,7 +122,8 @@ elif [ "$dang_tep" == 'sparse' ];then
     simg2img "$INPUT" "$file_img"
 elif [ "$dang_tep" == 'payload' ] || [ -n "$xacnhatpay" ];then
     echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
-    payload_extract -i "$INPUT" -X "$PVUGBIN" -o "$TMP" &>"$TMP/payload_extract.log" || killtree "Payload unpack error" & process_payload "$TMP/payload_extract.log"
+    payload_extract -i "$INPUT" -X "$PVUGBIN" -o "$TMP" &>"$TMP/payload_extract.log" || killtree "Payload unpack error" &
+    process_payload "$TMP/payload_extract.log"
     file_img="$TMP/$PVUGBIN.img"
 elif [ "$dang_tep" == 'super' ];then
     echo -e "$unpack_text_1 (${INPUT##*/}) ➠ ($PVUGBIN)...\n"
@@ -181,7 +183,7 @@ mkdir -p "$in_name" $OUTPUT/config
         echo "$dang_file" > "$info"
         fsck.f2fs "$file_img" &> "$fs_options"
     elif [ "$dang_file" == 'erofs' ];then
-        extract.erofs -T$threads -x -i "$file_img" -o "$OUTPUT" >$TMP/extract_erofs.log || killtree "\nextract.erofs error: ${namepv##*/}" "$in_name" &
+        extract.erofs -x -i "$file_img" -o "$OUTPUT" >$TMP/extract_erofs.log || killtree "\nextract.erofs error: ${namepv##*/}" "$in_name" &
         PIDK=$!
         while kill -0 $PIDK 2>/dev/null; do
         if [ -f $TMP/extract_erofs.log ];then
