Upload file

diff --git a/pio/src/main/assets/home/bin/unpack_img b/pio/src/main/assets/home/bin/unpack_img
--- a/pio/src/main/assets/home/bin/unpack_img
+++ b/pio/src/main/assets/home/bin/unpack_img
@@ -135,20 +135,20 @@ mkdir -p "$OUTPUT/${namepv##*/}" $OUTPUT/config
       imgextractor "$file_img" "$OUTPUT" >$TMP/imgextractor_ext.log
       echo "$dang_file" > "$OUTPUT/config/${namepv##*/}_info"
     elif [ "$dang_file" == 'f2fs' ];then
-      if [ "$ROT" == 0 ];then
-      killtree "Error Unpack: f2fs, $root_warning_text"
-      fi
-      #dump.f2fs -r -P -L -f -o "$OUTPUT/${namepv##*/}" "$file_img"
-      mkdir -p "$TMP/${namepv##*/}"
-      mount -r "$file_img" "$TMP/${namepv##*/}" &>$TMP/unpack_f2fs.log || {
-      umount -f -l "$TMP/${namepv##*/}" &>>$TMP/unpack_f2fs.log
-      rm -fr "$TMP/${namepv##*/}"
-      killtree "Extracting f2fs failed, check log: $TMP/unpack_f2fs.log"
-      }
-      getfscontex.py "$TMP/${namepv##*/}" "$OUTPUT/config" >>$TMP/unpack_f2fs.log
-      busybox cp -af "$TMP/${namepv##*/}" "$OUTPUT"
-      umount -f -l "$TMP/${namepv##*/}" &>>$TMP/unpack_f2fs.log
-      rm -fr "$TMP/${namepv##*/}"
+#      if [ "$ROT" == 0 ];then
+#      killtree "Error Unpack: f2fs, $root_warning_text"
+#      fi
+#      mkdir -p "$TMP/${namepv##*/}"
+      #dump.f2fs -r -L -f -o "$OUTPUT/${namepv##*/}" "$file_img"
+#      mount -t f2fs -r "$file_img" "$TMP/${namepv##*/}" &>$TMP/unpack_f2fs.log || {
+#      umount -f -l "$TMP/${namepv##*/}" &>>$TMP/unpack_f2fs.log
+#      rm -fr "$TMP/${namepv##*/}"
+#      killtree "Extracting f2fs failed, check log: $TMP/unpack_f2fs.log"; }
+#      getfscontex.py "$TMP/${namepv##*/}" "$OUTPUT/config" >>$TMP/unpack_f2fs.log
+#      busybox cp -af "$TMP/${namepv##*/}" "$OUTPUT"
+#      umount -f -l "$TMP/${namepv##*/}" &>>$TMP/unpack_f2fs.log
+#      rm -fr "$TMP/${namepv##*/}"
+      extract.f2fs "$file_img" "$OUTPUT" &>$TMP/unpack_f2fs.log || killtree "Extracting f2fs failed, check log: $TMP/unpack_f2fs.log";
       echo "$(stat -c%s "$file_img")" > "$OUTPUT/config/${namepv##*/}_size.txt"
       echo "$dang_file" > "$OUTPUT/config/${namepv##*/}_info"
       echo "$(fsck.f2fs "$file_img" | grep 'superblock features' | grep -cm1 ro)" > "$OUTPUT/config/${namepv##*/}_f2fs_ro"
